### ISSUE TITLE
Replace the list of matched user id's with a list of user data

### ISSUE THREAD

**Issue by nateirwin25** [smparkin/NiTheCodersSay#117]
When the jam view is clicked on, a request is made to the server and the server returns a list of ids. This means the frontend then has to make a request for each user id to populate their data. Instead, when the frontend hits '/getNearby', send a list of json user objects with the following fields: name, bio, and id. Make a new branch off of sprint5 for this.

**Comment by meinfr13nd** [comment]
won't do
